_target_: src.datamodules.intent_datamodule.IntentDataModule
data_dir: ${data_dir}  # data_dir is specified in config.yaml
tokenizer_dir: /tmp/
batch_size: 64
train_val_test_split: [0.8, 0.1, 0.1] # split data with this ratio
num_workers: 6
pin_memory: False
num_labels: 6 # labels: goal_info, match_info, match_result, substitution, penalty, card_info